### ISSUE TITLE
guzzle/guzzle is deprecated

### ISSUE THREAD

**Issue by andrewandante** [silverstripeltd/deploynaut-metrics#8]
We should upgrade this bad boy to use `guzzlehttp/guzzle`, preferably ~6.0 so that we are in line with the dashboard.

**Comment by stojg** [comment]
Fixed in https://github.com/silverstripeltd/deploynaut-metrics/pull/9 most of the time fixing this was messing with the circle.ci settings

**Comment by andrewandante** [comment]
Thanks! Merged.
